only_rules:
  - colon
  - fatal_error_message
  - implicitly_unwrapped_optional
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - return_arrow_whitespace
  - trailing_newline
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - cyclomatic_complexity
  - function_body_length
  - nesting
  - identifier_name
  - line_length
  - custom_rules

excluded:
  - Carthage
  - Pods
  - .build

colon:
  apply_to_dictionaries: false

indentation: 2

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

function_body_length:
  warning: 40
  error: 60
  ignores_comments: true
  ignores_empty_functions: true

nesting:
  type_level: 2
  statement_level: 5
  severity: warning

identifier_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_function_declarations: true

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
  no_direct_standard_out_logs:
    name: "No direct standard out logs"
    regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\.dump)\\s*\\("
    match_kinds:
      - identifier
    message: "Don't commit `print`, `debugPrint`, or `dump`. Use a logging system instead or wrap with `#if DEBUG`."
    severity: warning
  no_file_literal:
    name: "#file is disallowed"
    regex: "\\b#file\\b"
    match_kinds:
      - identifier
    message: "Use #fileID instead of #file."
  no_filepath_literal:
    name: "#filePath is disallowed"
    regex: "\\b#filePath\\b"
    match_kinds:
      - identifier
    message: "Use #fileID instead of #filePath."
